local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>fg', builtin.git_files, { desc = 'Telescope files under git' })
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fl', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })